name: deploy pr
on:
  pull_request:
    branches:
      - github-action
  push:
    branches:
      - github-action
jobs:
  runs-on: windows-latest
  steps:
    - name: checkout repository
    - uses: actions/checkout@v3
    - name: setup java
    - uses: actions/setup-java@v3
      with:
        node-version: '17'
    - name: build
      run: mvn clean install -DskipTests
